### ISSUE TITLE
How to use Nix 2.14?

### ISSUE THREAD

**Issue by srid** [nixbuild/nix-quick-install-action#28]
I tried:

```yaml
      - uses: nixbuild/nix-quick-install-action@master
        with:
          # We use newer Nix for:
          # - https://github.com/NixOS/nix/issues/7263
          # - https://github.com/NixOS/nix/issues/7026
          nix_version: 2.14.1
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
```

But this throws:

```
zstd: /*stdin*\: unsupported format 
Error: Process completed with exit code 1.
```

https://github.com/srid/haskell-flake/actions/runs/4411324946/jobs/7729732345
