### ISSUE TITLE
feature request: integrate `nothing-but-nix` to free disk space

### ISSUE THREAD

**Issue by peterbecich** [nixbuild/nix-quick-install-action#68]
Can https://github.com/wimpysworld/nothing-but-nix be integrated into `nix-quick-install-action`?

Using both in one GitHub Action yields an error for me. However, the concept sounds like a good one.

**Comment by sporieg-qi** [comment]
Late to the party, @peterbecich  what you need to do is tell nothing-but-nix to let quick install have write permisions.

```
    - uses: wimpysworld/nothing-but-nix@main
      with:
        nix-permission-edict: true
    - name: install nix
      uses: nixbuild/nix-quick-install-action@v33
```
